[project]
name = "demo-crewai-travel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.76.2",
    "jupyter>=1.1.1",
    "llama-index-embeddings-huggingface>=0.2.3",
    "llama-index>=0.10.9",
]
